/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/ABSBasketModel.xml' path='doc/members/member[@name="T:ABSBasketModel"]/*' />
public static partial class ABSBasketModel {
  /// <include file='swig/ABSBasketModel.xml' path='doc/members/member[@name="M:ABSBasketModel_ComputeDistributions"]/*' />
  public static void ComputeDistributions(bool wantProbability, int basketSize, double totalPrincipal, BaseEntity.Toolkit.Base.CopulaType copulaType, int dfCommon, int dfIdiosyncratic, double[] copulaParams, double[] corrData, int[] corrDates, int integrationPointsFirst, int integrationPointsSecond, double[] probabilities, double[] defaultValues, double[] survivalValues, double gridSize, Curves.Curve2D distributions) {
    BaseEntityPINVOKE.ABSBasketModel_ComputeDistributions(wantProbability, basketSize, totalPrincipal, (int)copulaType, dfCommon, dfIdiosyncratic, copulaParams, corrData, corrDates, integrationPointsFirst, integrationPointsSecond, probabilities, defaultValues, survivalValues, gridSize, Curves.Curve2D.getCPtr(distributions));
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
