/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/AnalyticCDOSquaredModel.xml' path='doc/members/member[@name="T:AnalyticCDOSquaredModel"]/*' />
public static partial class AnalyticCDOSquaredModel {
  /// <include file='swig/AnalyticCDOSquaredModel.xml' path='doc/members/member[@name="M:AnalyticCDOSquaredModel_ComputeDistributions"]/*' />
  public static void ComputeDistributions(bool wantProbability, BaseEntity.Toolkit.Base.Dt asOf, BaseEntity.Toolkit.Base.Dt maturity, int stepSize, BaseEntity.Toolkit.Base.TimeUnit stepUnit, BaseEntity.Toolkit.Base.CopulaType copulaType, int dfCommon, int dfIdiosyncratic, int integrationPointsFirst, int integrationPointsSecond, double[] corrData, Toolkit.Native.INativeCurve[] survCurves, double[] recoveryMeans, double[] principals, double[] attachments, double[] detachments, double[] lossLevels, double gridSize, Curves.Curve2D lossDistributions) {
    BaseEntityPINVOKE.AnalyticCDOSquaredModel_ComputeDistributions(wantProbability, asOf, maturity, stepSize, (int)stepUnit, (int)copulaType, dfCommon, dfIdiosyncratic, integrationPointsFirst, integrationPointsSecond, corrData, survCurves, recoveryMeans, principals, attachments, detachments, lossLevels, gridSize, Curves.Curve2D.getCPtr(lossDistributions));
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
