/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/BK.xml' path='doc/members/member[@name="T:BK"]/*' />
public static partial class BK {
  /// <include file='swig/BK.xml' path='doc/members/member[@name="M:BK_P"]/*' />
  public static double[] P(int N, double dt, double x0, double alpha, double sigma, double[] theta) 
  {
    double[] ret = BaseEntityPINVOKE.BK_P(N, dt, x0, alpha, sigma, theta);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }


}
}
