/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/CliquetOption.xml' path='doc/members/member[@name="T:CliquetOption"]/*' />
public static partial class CliquetOption {
  /// <include file='swig/CliquetOption.xml' path='doc/members/member[@name="M:CliquetOption_P"]/*' />
  public static double P(BaseEntity.Toolkit.Base.OptionStyle style, BaseEntity.Toolkit.Base.OptionType type, double T, double[] resets, double S, double K, double r, double d, double v) {
    double ret = BaseEntityPINVOKE.CliquetOption_P((int)style, (int)type, T, resets, S, K, r, d, v);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/CliquetOption.xml' path='doc/members/member[@name="M:CliquetOption_ImpliedVolatility"]/*' />
  public static double ImpliedVolatility(BaseEntity.Toolkit.Base.OptionStyle style, BaseEntity.Toolkit.Base.OptionType type, double T, double[] resets, double S, double K, double r, double d, double price) {
    double ret = BaseEntityPINVOKE.CliquetOption_ImpliedVolatility((int)style, (int)type, T, resets, S, K, r, d, price);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
