/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/ComovementBasketModel.xml' path='doc/members/member[@name="T:ComovementBasketModel"]/*' />
public static partial class ComovementBasketModel {
  /// <include file='swig/ComovementBasketModel.xml' path='doc/members/member[@name="M:ComovementBasketModel_ComputeDistributions"]/*' />
  public static void ComputeDistributions(bool wantProbability, int startDateIndex, int stopDateIndex, Toolkit.Native.INativeCurve[] survivalCurves, double[] principals, double[] recoveryRates, double[] recoveryDispersions, Toolkit.Native.INativeCurve[] refinanceCurves, double[] maturities, double gridSize, Curves.Curve2D lossDistributions, Curves.Curve2D amorDistributions) {
    BaseEntityPINVOKE.ComovementBasketModel_ComputeDistributions(wantProbability, startDateIndex, stopDateIndex, survivalCurves, principals, recoveryRates, recoveryDispersions, refinanceCurves, maturities, gridSize, Curves.Curve2D.getCPtr(lossDistributions), Curves.Curve2D.getCPtr(amorDistributions));
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
