/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.ComponentModel;

namespace BaseEntity.Toolkit.Curves {


  public class DelegateCurveInterp : BaseEntity.Toolkit.Numerics.Interp {
  private HandleRef swigCPtr;

  public DelegateCurveInterp(IntPtr cPtr, bool cMemoryOwn) : base(BaseEntityPINVOKE.DelegateCurveInterpUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  /// <exclude />
  public static HandleRef getCPtr(DelegateCurveInterp obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  /// <exclude />
  ~DelegateCurveInterp() {
    Dispose();
  }

  /// <exclude />
  public override void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      BaseEntityPINVOKE.delete_DelegateCurveInterp(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
    base.Dispose();
  }

      public delegate double EvaluateFn(IntPtr curve, double x, int index);
      public delegate void InitializeFn(IntPtr curve);
    
  /// <include file='swig/DelegateCurveInterp.xml' path='doc/members/member[@name="M:new_DelegateCurveInterp"]/*' />
  public DelegateCurveInterp(DelegateCurveInterp.InitializeFn initFn, DelegateCurveInterp.EvaluateFn evalFn) : this(BaseEntityPINVOKE.new_DelegateCurveInterp(initFn, evalFn), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
