/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/ExchangeOption.xml' path='doc/members/member[@name="T:ExchangeOption"]/*' />
public static partial class ExchangeOption {
  /// <include file='swig/ExchangeOption.xml' path='doc/members/member[@name="M:ExchangeOption_P"]/*' />
  public static double P(BaseEntity.Toolkit.Base.OptionStyle style, BaseEntity.Toolkit.Base.OptionType type, double T, double Q1, double Q2, double F1, double F2, double r, double vol1, double vol2, double correlation) {
    double ret = BaseEntityPINVOKE.ExchangeOption_P((int)style, (int)type, T, Q1, Q2, F1, F2, r, vol1, vol2, correlation);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
