/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/ForwardLossBasketModel.xml' path='doc/members/member[@name="T:ForwardLossBasketModel"]/*' />
public static partial class ForwardLossBasketModel {
  /// <include file='swig/ForwardLossBasketModel.xml' path='doc/members/member[@name="M:ForwardLossBasketModel_CalculateProbabilities__SWIG_0"]/*' />
  public static void CalculateProbabilities(int numStates, double periodLength, double stepLength, double[] initialProbabilities, double[] transitionRates, double[] resultingProbabilities) {
    BaseEntityPINVOKE.ForwardLossBasketModel_CalculateProbabilities__SWIG_0(numStates, periodLength, stepLength, initialProbabilities, transitionRates, resultingProbabilities);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/ForwardLossBasketModel.xml' path='doc/members/member[@name="M:ForwardLossBasketModel_CalculateProbabilities__SWIG_1"]/*' />
  public static void CalculateProbabilities(int numStates, double periodLength, double stepLength, double[] initialProbabilities, double[] transitionRates, double expectedDefault, double[] resultingProbabilities) {
    BaseEntityPINVOKE.ForwardLossBasketModel_CalculateProbabilities__SWIG_1(numStates, periodLength, stepLength, initialProbabilities, transitionRates, expectedDefault, resultingProbabilities);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
