/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/HullWhite.xml' path='doc/members/member[@name="T:HullWhite"]/*' />
public static partial class HullWhite {
  /// <include file='swig/HullWhite.xml' path='doc/members/member[@name="M:HullWhite_P"]/*' />
  public static double[] P(int N, double dt, double x0, double[] theta, double alpha, double sigma, double beta) 
  {
    double[] ret = BaseEntityPINVOKE.HullWhite_P(N, dt, x0, theta, alpha, sigma, beta);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }


}
}
