/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/HullWhiteDynamicBasketModel.xml' path='doc/members/member[@name="T:HullWhiteDynamicBasketModel"]/*' />
public static partial class HullWhiteDynamicBasketModel {
  /// <include file='swig/HullWhiteDynamicBasketModel.xml' path='doc/members/member[@name="M:HullWhiteDynamicBasketModel_ComputeDistributions"]/*' />
  public static void ComputeDistributions(bool wantProbability, int startDateIndex, int stopDateIndex, double[] parameters, Toolkit.Native.INativeCurve[] survivalCurves, double[] principals, double[] recoveryMeans, Curves.Curve2D distributions) {
    BaseEntityPINVOKE.HullWhiteDynamicBasketModel_ComputeDistributions(wantProbability, startDateIndex, stopDateIndex, parameters, survivalCurves, principals, recoveryMeans, Curves.Curve2D.getCPtr(distributions));
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
