/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/MarkovianBasketModel.xml' path='doc/members/member[@name="T:MarkovianBasketModel"]/*' />
public static partial class MarkovianBasketModel {
  /// <include file='swig/MarkovianBasketModel.xml' path='doc/members/member[@name="M:MarkovianBasketModel_ComputeDistributions"]/*' />
  public static void ComputeDistributions(BaseEntity.Toolkit.Base.Dt startDate, BaseEntity.Toolkit.Base.Dt stopDate, double[] lambdas, double[] scales, bool singleJump, Curves.Curve2D distributions) {
    BaseEntityPINVOKE.MarkovianBasketModel_ComputeDistributions(startDate, stopDate, lambdas, scales, singleJump, Curves.Curve2D.getCPtr(distributions));
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
