/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/MonteCarloCDOSquaredModel.xml' path='doc/members/member[@name="T:MonteCarloCDOSquaredModel"]/*' />
public static partial class MonteCarloCDOSquaredModel {
  /// <include file='swig/MonteCarloCDOSquaredModel.xml' path='doc/members/member[@name="M:MonteCarloCDOSquaredModel_ComputeDistributions"]/*' />
  public static void ComputeDistributions(bool wantProbability, BaseEntity.Toolkit.Base.Dt asOf, BaseEntity.Toolkit.Base.Dt maturity, int stepSize, BaseEntity.Toolkit.Base.TimeUnit stepUnit, BaseEntity.Toolkit.Base.CopulaType copulaType, int dfCommon, int dfIdiosyncratic, double[] corrData, Toolkit.Native.INativeCurve[] survCurves, double[] recoveryMeans, double[] recoveryDispersions, double[] principals, double[] attachments, double[] detachments, double[] lossLevels, int runs, bool useQuasiRng, Curves.Curve2D lossDistributions, BaseEntity.Toolkit.Base.Dt[] cdoMaturities, uint seed) {
    BaseEntityPINVOKE.MonteCarloCDOSquaredModel_ComputeDistributions(wantProbability, asOf, maturity, stepSize, (int)stepUnit, (int)copulaType, dfCommon, dfIdiosyncratic, corrData, survCurves, recoveryMeans, recoveryDispersions, principals, attachments, detachments, lossLevels, runs, useQuasiRng, Curves.Curve2D.getCPtr(lossDistributions), cdoMaturities, seed);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
