/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.ComponentModel;

namespace BaseEntity.Toolkit.Numerics {


/// <include file='swig/MultivariateDistribution.xml' path='doc/members/member[@name="T:MultivariateDistribution"]/*' />
[TypeConverter(typeof(ExpandableObjectConverter))]
public partial class MultivariateDistribution : IDisposable {
  private HandleRef swigCPtr;

  /// <exclude />
  protected bool swigCMemOwn;

  public MultivariateDistribution(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  /// <exclude />
  public static HandleRef getCPtr(MultivariateDistribution obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  /// <exclude />
  ~MultivariateDistribution() {
    Dispose();
  }

  /// <exclude />
  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      BaseEntityPINVOKE.delete_MultivariateDistribution(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

			///<exclude/>
			[SecurityPermission(SecurityAction.Demand, SerializationFormatter=true)]
			public virtual void GetObjectData(SerializationInfo info, StreamingContext context)
			{ 
			}

			public MultivariateDistribution(IntPtr cPtr, 
																				bool cMemoryOwn, 
																				SerializationInfo info,
																				StreamingContext context)
			{
				swigCMemOwn = cMemoryOwn;
				swigCPtr = new HandleRef(this, cPtr);
			}
			
  /// <include file='swig/MultivariateDistribution.xml' path='doc/members/member[@name="M:MultivariateDistribution_pdf"]/*' />
  public virtual double pdf(double[] x) {
    double ret = BaseEntityPINVOKE.MultivariateDistribution_pdf(swigCPtr, x);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/MultivariateDistribution.xml' path='doc/members/member[@name="M:MultivariateDistribution_cdf"]/*' />
  public virtual double cdf(double[] x) {
    double ret = BaseEntityPINVOKE.MultivariateDistribution_cdf(swigCPtr, x);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/MultivariateDistribution.xml' path='doc/members/member[@name="M:MultivariateDistribution_dimension"]/*' />
  public virtual int dimension() {
    int ret = BaseEntityPINVOKE.MultivariateDistribution_dimension(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
