/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.ComponentModel;

namespace BaseEntity.Toolkit.Numerics {


/// <include file='swig/NLS.xml' path='doc/members/member[@name="T:NLS"]/*' />
[TypeConverter(typeof(ExpandableObjectConverter))]
public partial class NLS : Optimizer {
  private HandleRef swigCPtr;

  public NLS(IntPtr cPtr, bool cMemoryOwn) : base(BaseEntityPINVOKE.NLSUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  /// <exclude />
  public static HandleRef getCPtr(NLS obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  /// <exclude />
  ~NLS() {
    Dispose();
  }

  /// <exclude />
  public override void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      BaseEntityPINVOKE.delete_NLS(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
    base.Dispose();
  }

  /// <include file='swig/NLS.xml' path='doc/members/member[@name="M:new_NLS__SWIG_0"]/*' />
  public NLS(int dimension) : this(BaseEntityPINVOKE.new_NLS__SWIG_0(dimension), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/NLS.xml' path='doc/members/member[@name="M:new_NLS__SWIG_1"]/*' />
  public NLS(NLS optimizer) : this(BaseEntityPINVOKE.new_NLS__SWIG_1(NLS.getCPtr(optimizer)), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/NLS.xml' path='doc/members/member[@name="M:NLS_clone"]/*' />
  public override Optimizer clone() {
    IntPtr cPtr = BaseEntityPINVOKE.NLS_clone(swigCPtr);
    Optimizer ret = (cPtr == IntPtr.Zero) ? null : new Optimizer(cPtr, true);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
