/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BaseEntity.Toolkit.Base {

/// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="T:OptionBarrierFlag"]/*' />

  [System.Flags] public enum  OptionBarrierFlag {

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.Regular"]/*' />
  Regular = 0,

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.InvertBaseCcy"]/*' />
  InvertBaseCcy = 0x04,

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.Digital"]/*' />
  Digital = 0x10,

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.PayAtBarrierHit"]/*' />
  PayAtBarrierHit = 0x20,

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.PayInForeignCurrency"]/*' />
  PayInForeignCurrency = 0x40,

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.PayAsset"]/*' />
  PayAsset = 0x40,

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.NoTouch"]/*' />
  NoTouch = 0x100,

  /// <include file='swig/OptionBarrierFlag.xml' path='doc/members/member[@name="F:OptionBarrierFlag.OneTouch"]/*' />
  OneTouch = 0x200
}
}
