/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.ComponentModel;
using BaseEntity.Shared;

namespace BaseEntity.Toolkit.Numerics {


  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="T:PCHIP"]/*' />
  [Serializable]
  public class PCHIP : Interp, INativeSerializable {
  private HandleRef swigCPtr;

  public PCHIP(IntPtr cPtr, bool cMemoryOwn) : base(BaseEntityPINVOKE.PCHIPUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  /// <exclude />
  public static HandleRef getCPtr(PCHIP obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  /// <exclude />
  ~PCHIP() {
    Dispose();
  }

  /// <exclude />
  public override void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      BaseEntityPINVOKE.delete_PCHIP(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
    base.Dispose();
  }

			///<exclude/>
			[SecurityPermission(SecurityAction.Demand,SerializationFormatter=true)]
			public override void GetObjectData(SerializationInfo info, StreamingContext context)
			{ 
				base.GetObjectData(info, context);
				info.AddValue("b_", GetpublicData_B());
				info.AddValue("c_", GetpublicData_C());
				info.AddValue("d_", GetpublicData_D());
			}

			public PCHIP(IntPtr cPtr, 
										 bool cMemoryOwn, 
										 SerializationInfo info,
										 StreamingContext context) : base(BaseEntityPINVOKE.PCHIPUpcast(cPtr), cMemoryOwn, info, context)
			{
				swigCPtr = new HandleRef(this, cPtr);
			}

			///<exclude/>
			protected PCHIP(SerializationInfo info, StreamingContext context) : this(BaseEntityPINVOKE.new_PCHIP__SWIG_0(), true, info, context)
			{
				double[] b = (double[])info.GetValue("b_", typeof(double[]));
				double[] c = (double[])info.GetValue("c_", typeof(double[]));
				double[] d = (double[])info.GetValue("d_", typeof(double[]));

				SetpublicData_B(b);
				SetpublicData_C(c);
				SetpublicData_D(d);
			}
			
  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:new_PCHIP__SWIG_0"]/*' />
  public PCHIP() : this(BaseEntityPINVOKE.new_PCHIP__SWIG_0(), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:new_PCHIP__SWIG_1"]/*' />
  public PCHIP(Extrap upperExtrap, Extrap lowerExtrap) : this(BaseEntityPINVOKE.new_PCHIP__SWIG_1(Extrap.getCPtr(upperExtrap), Extrap.getCPtr(lowerExtrap)), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:new_PCHIP__SWIG_2"]/*' />
  public PCHIP(PCHIP interp) : this(BaseEntityPINVOKE.new_PCHIP__SWIG_2(PCHIP.getCPtr(interp)), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:PCHIP_clone"]/*' />
  public override Interp clone() 
  {
    IntPtr cPtr = BaseEntityPINVOKE.PCHIP_clone(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    if( cPtr == IntPtr.Zero ) {
      return null;
    }
    else {
      string typeName = String.Format(Interp.TypeFormatString, BaseEntityPINVOKE.Interp_typeName( new HandleRef(this, cPtr)));
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();

      Type type = Type.GetType( typeName, true );
      object o = type.Assembly.CreateInstance(type.FullName, false, 
                                              System.Reflection.BindingFlags.CreateInstance|System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance, 
                                              null, new object[]{cPtr, true}, null, null);

      return (Interp)o;
    }
  }


  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:PCHIP_GetpublicData_B"]/*' />
  public double[] GetpublicData_B() 
  {
    double[] ret = BaseEntityPINVOKE.PCHIP_GetpublicData_B(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }


  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:PCHIP_SetpublicData_B"]/*' />
  public void SetpublicData_B(double[] array) {
    BaseEntityPINVOKE.PCHIP_SetpublicData_B(swigCPtr, array);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:PCHIP_GetpublicData_C"]/*' />
  public double[] GetpublicData_C() 
  {
    double[] ret = BaseEntityPINVOKE.PCHIP_GetpublicData_C(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }


  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:PCHIP_SetpublicData_C"]/*' />
  public void SetpublicData_C(double[] array) {
    BaseEntityPINVOKE.PCHIP_SetpublicData_C(swigCPtr, array);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:PCHIP_GetpublicData_D"]/*' />
  public double[] GetpublicData_D() 
  {
    double[] ret = BaseEntityPINVOKE.PCHIP_GetpublicData_D(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }


  /// <include file='swig/PCHIP.xml' path='doc/members/member[@name="M:PCHIP_SetpublicData_D"]/*' />
  public void SetpublicData_D(double[] array) {
    BaseEntityPINVOKE.PCHIP_SetpublicData_D(swigCPtr, array);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
