/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/PowerOption.xml' path='doc/members/member[@name="T:PowerOption"]/*' />
public static partial class PowerOption {
  /// <include file='swig/PowerOption.xml' path='doc/members/member[@name="M:PowerOption_P"]/*' />
  public static double P(double T, double bf, double K1, double K2, double r, double v) {
    double ret = BaseEntityPINVOKE.PowerOption_P(T, bf, K1, K2, r, v);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
