/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.ComponentModel;

namespace BaseEntity.Toolkit.Models.BGM.Native {


/// <include file='swig/RateSystem.xml' path='doc/members/member[@name="T:RateSystem"]/*' />
[TypeConverter(typeof(ExpandableObjectConverter))]
public partial class RateSystem : IDisposable {
  private HandleRef swigCPtr;

  /// <exclude />
  protected bool swigCMemOwn;

  public RateSystem(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  /// <exclude />
  public static HandleRef getCPtr(RateSystem obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  /// <exclude />
  ~RateSystem() {
    Dispose();
  }

  /// <exclude />
  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      BaseEntityPINVOKE.delete_RateSystem(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  /// <include file='swig/RateSystem.xml' path='doc/members/member[@name="M:new_RateSystem"]/*' />
  public RateSystem() : this(BaseEntityPINVOKE.new_RateSystem(), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/RateSystem.xml' path='doc/members/member[@name="M:RateSystem_clone"]/*' />
  public RateSystem clone() {
    IntPtr cPtr = BaseEntityPINVOKE.RateSystem_clone(swigCPtr);
    RateSystem ret = (cPtr == IntPtr.Zero) ? null : new RateSystem(cPtr, true);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/RateSystem.xml' path='doc/members/member[@name="M:RateSystem_initialize"]/*' />
  public void initialize(int rateCount, int dateCount) {
    BaseEntityPINVOKE.RateSystem_initialize(swigCPtr, rateCount, dateCount);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/RateSystem.xml' path='doc/members/member[@name="M:RateSystem_set_up"]/*' />
  public void set_up(int dateIndex, int nodeCount) {
    BaseEntityPINVOKE.RateSystem_set_up(swigCPtr, dateIndex, nodeCount);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
