/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


public static partial class SabrModel {
  /// <include file='swig/SabrModel.xml' path='doc/members/member[@name="M:SabrModel_BlackVolatility__SWIG_0"]/*' />
  public static double BlackVolatility(double zeta, double beta, double nu, double rho, double moneyness, double time) {
    double ret = BaseEntityPINVOKE.SabrModel_BlackVolatility__SWIG_0(zeta, beta, nu, rho, moneyness, time);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/SabrModel.xml' path='doc/members/member[@name="M:SabrModel_BlackVolatility__SWIG_1"]/*' />
  public static double BlackVolatility(double alpha, double beta, double nu, double rho, double forward, double strike, double time) {
    double ret = BaseEntityPINVOKE.SabrModel_BlackVolatility__SWIG_1(alpha, beta, nu, rho, forward, strike, time);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/SabrModel.xml' path='doc/members/member[@name="M:SabrModel_CalibrateParameters"]/*' />
  public static void CalibrateParameters(double time, double[] moneyness, double[] volatilities, double[] lowerBounds, double[] upperBounds, ref double zeta, ref double beta, ref double nu, ref double rho) {
    BaseEntityPINVOKE.SabrModel_CalibrateParameters(time, moneyness, volatilities, lowerBounds, upperBounds, ref zeta, ref beta, ref nu, ref rho);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
