/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.ComponentModel;

namespace BaseEntity.Toolkit.Numerics {


/// <include file='swig/Statistics.xml' path='doc/members/member[@name="T:Statistics"]/*' />
[TypeConverter(typeof(ExpandableObjectConverter))]
public partial class Statistics : IDisposable {
  private HandleRef swigCPtr;

  /// <exclude />
  protected bool swigCMemOwn;

  public Statistics(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  /// <exclude />
  public static HandleRef getCPtr(Statistics obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  /// <exclude />
  ~Statistics() {
    Dispose();
  }

  /// <exclude />
  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      BaseEntityPINVOKE.delete_Statistics(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Mean"]/*' />
  public static double Mean(double[] data) {
    double ret = BaseEntityPINVOKE.Statistics_Mean(data);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Variance__SWIG_0"]/*' />
  public static double Variance(double[] data) {
    double ret = BaseEntityPINVOKE.Statistics_Variance__SWIG_0(data);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Variance__SWIG_1"]/*' />
  public static double Variance(double[] data, double mean) {
    double ret = BaseEntityPINVOKE.Statistics_Variance__SWIG_1(data, mean);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_StdDev__SWIG_0"]/*' />
  public static double StdDev(double[] data) {
    double ret = BaseEntityPINVOKE.Statistics_StdDev__SWIG_0(data);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_StdDev__SWIG_1"]/*' />
  public static double StdDev(double[] data, double mean) {
    double ret = BaseEntityPINVOKE.Statistics_StdDev__SWIG_1(data, mean);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Skew__SWIG_0"]/*' />
  public static double Skew(double[] data) {
    double ret = BaseEntityPINVOKE.Statistics_Skew__SWIG_0(data);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Skew__SWIG_1"]/*' />
  public static double Skew(double[] data, double stddev, double mean) {
    double ret = BaseEntityPINVOKE.Statistics_Skew__SWIG_1(data, stddev, mean);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Kurtosis__SWIG_0"]/*' />
  public static double Kurtosis(double[] data) {
    double ret = BaseEntityPINVOKE.Statistics_Kurtosis__SWIG_0(data);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Kurtosis__SWIG_1"]/*' />
  public static double Kurtosis(double[] data, double stddev, double mean) {
    double ret = BaseEntityPINVOKE.Statistics_Kurtosis__SWIG_1(data, stddev, mean);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:Statistics_Histogram"]/*' />
  public static double[] Histogram(double[] binNodes, double[] data) 
  {
    double[] ret = BaseEntityPINVOKE.Statistics_Histogram(binNodes, data);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }


  /// <include file='swig/Statistics.xml' path='doc/members/member[@name="M:new_Statistics"]/*' />
  public Statistics() : this(BaseEntityPINVOKE.new_Statistics(), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

}
}
