/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.ComponentModel;

namespace BaseEntity.Toolkit.Util {


/// <include file='swig/Timer.xml' path='doc/members/member[@name="T:Timer"]/*' />
[TypeConverter(typeof(ExpandableObjectConverter))]
public partial class Timer : IDisposable {
  private HandleRef swigCPtr;

  /// <exclude />
  protected bool swigCMemOwn;

  public Timer(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  /// <exclude />
  public static HandleRef getCPtr(Timer obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  /// <exclude />
  ~Timer() {
    Dispose();
  }

  /// <exclude />
  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      BaseEntityPINVOKE.delete_Timer(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  /// <include file='swig/Timer.xml' path='doc/members/member[@name="M:new_Timer"]/*' />
  public Timer() : this(BaseEntityPINVOKE.new_Timer(), true) {
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/Timer.xml' path='doc/members/member[@name="M:Timer_start"]/*' />
  public void start() {
    BaseEntityPINVOKE.Timer_start(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/Timer.xml' path='doc/members/member[@name="M:Timer_stop"]/*' />
  public double stop() {
    double ret = BaseEntityPINVOKE.Timer_stop(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Timer.xml' path='doc/members/member[@name="M:Timer_resume"]/*' />
  public void resume() {
    BaseEntityPINVOKE.Timer_resume(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <include file='swig/Timer.xml' path='doc/members/member[@name="M:Timer_getElapsed"]/*' />
  public double getElapsed() {
    double ret = BaseEntityPINVOKE.Timer_getElapsed(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <include file='swig/Timer.xml' path='doc/members/member[@name="M:Timer_isRunning"]/*' />
  public bool isRunning() {
    bool ret = BaseEntityPINVOKE.Timer_isRunning(swigCPtr);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
