/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/TwoFactorAffineJ.xml' path='doc/members/member[@name="T:TwoFactorAffineJ"]/*' />
public static partial class TwoFactorAffineJ {
  /// <include file='swig/TwoFactorAffineJ.xml' path='doc/members/member[@name="M:TwoFactorAffineJ_P"]/*' />
  public static double P(int steps, double T, double x0, double kappa_x, double sigma_x, double mu_x, double ell_x, double y0, double kappa_y, double theta_y, double sigma_y) {
    double ret = BaseEntityPINVOKE.TwoFactorAffineJ_P(steps, T, x0, kappa_x, sigma_x, mu_x, ell_x, y0, kappa_y, theta_y, sigma_y);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
