/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.26
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

namespace BaseEntity.Toolkit.Models {


/// <include file='swig/Vasicek.xml' path='doc/members/member[@name="T:Vasicek"]/*' />
public static partial class Vasicek {
  /// <include file='swig/Vasicek.xml' path='doc/members/member[@name="M:Vasicek_P"]/*' />
  public static double P(double T, double x0, double theta, double kappa, double sigma) {
    double ret = BaseEntityPINVOKE.Vasicek_P(T, x0, theta, kappa, sigma);
    if (BaseEntityPINVOKE.SWIGPendingException.Pending) throw BaseEntityPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
}
